import { AlertsResponse } from '../../domains/alerts/models/alert.models';

export const ALERTS_RESPONSE: AlertsResponse = {
  generatedAt: '2026-09-18T12:00:00.000Z',
  alerts: [
    {
      id: 'alert-critical-cutting',
      plantId: 'plant-north',
      lineId: 'cutting-01',
      lineName: 'Corte 01',
      severity: 'critical',
      status: 'active',
      message: 'Presión hidráulica por debajo del límite seguro',
      startedAt: '2026-09-18T08:15:00.000Z',
      resolvedAt: null,
    },
    {
      id: 'alert-critical-welding',
      plantId: 'plant-north',
      lineId: 'welding-01',
      lineName: 'Soldadura 01',
      severity: 'critical',
      status: 'active',
      message: 'Temperatura fuera de rango',
      startedAt: '2026-09-18T10:48:00.000Z',
      resolvedAt: null,
    },
    {
      id: 'alert-warning-forming',
      plantId: 'plant-north',
      lineId: 'forming-01',
      lineName: 'Conformado 01',
      severity: 'warning',
      status: 'active',
      message: 'Rendimiento sostenido por debajo del 80%',
      startedAt: '2026-09-18T09:32:00.000Z',
      resolvedAt: null,
    },
    {
      id: 'alert-warning-cutting-resolved',
      plantId: 'plant-north',
      lineId: 'cutting-01',
      lineName: 'Corte 01',
      severity: 'warning',
      status: 'resolved',
      message: 'Cambio de herramienta excedió el tiempo objetivo',
      startedAt: '2026-09-18T07:40:00.000Z',
      resolvedAt: '2026-09-18T08:02:00.000Z',
    },
    {
      id: 'alert-info-finishing',
      plantId: 'plant-north',
      lineId: 'finishing-01',
      lineName: 'Acabado 01',
      severity: 'info',
      status: 'active',
      message: 'Telemetría intermitente en estación de inspección',
      startedAt: '2026-09-18T11:30:00.000Z',
      resolvedAt: null,
    },
    {
      id: 'alert-info-cutting-resolved',
      plantId: 'plant-north',
      lineId: 'cutting-01',
      lineName: 'Corte 01',
      severity: 'info',
      status: 'resolved',
      message: 'Orden de producción iniciada',
      startedAt: '2026-09-18T06:00:00.000Z',
      resolvedAt: '2026-09-18T06:01:00.000Z',
    },
  ],
};
